language: rust

before_script:
  - rustup component add rustfmt-preview 

script:
  - make check
  - make test
  - make test-bottom

notifications:
  email:
    on_success: never
    on_failure: never
