language: rust
rust:
  - nightly

before_script:
  - rustup component add rustfmt-preview --toolchain nightly

script:
  - make check
  - cargo test
  - make test-light

notifications:
  email:
    on_success: never
    on_failure: never
