[package]
name = "meow"
version = "0.1.0"
authors = ["tigercosmos <phy.tiger@gmail.com>"]

[dependencies]
imageproc = "0.15.0"
rusttype = "0.5"
image = "0.19.0"
serde_json = "*"
serde = "*"
serde_derive = "*"
clap = {version = "~2.32.0", features = ["yaml"]}
